### Insere Usuario

POST http://localhost:8080/usuario
Content-Type: application/json

{
    "login" : "teste",
    "password" : "teste",
    "email" : "email@teste.com",
    "nome" : "teste123",
    "endereco" : "Rua teste",
    "cpf" : 123,
    "instagram" : "teste.instagram",
    "twitter" : "teste.twitter",
    "telefone" : 999999999

}